version: '3.8'

services:
  postgresUser:
    container_name: USER
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
    volumes:
      - user:/var/lib/postgresql/data
    command: -p 5433
volumes:
  user: