version: '3.8'

services:
  postgresRent:
    container_name: RENT
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rentdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - rent:/var/lib/postgresql/data
volumes:
  rent: